### ISSUE TITLE
V0.0.1 - no issues!

### ISSUE THREAD

**Issue by Ilovegym66** [BuZZy1337/ioBroker.roadtraffic#1]
Hi,
thank you for this fantastic Adapter! installed, works fine, no errors, no issues now.
System: Linux Mint 18.3, Node 8.15, NPM 6.5.0, js-controller 1.5.7

Top!

**Comment by BuZZy1337** [comment]
Haha woooow.. That was quick!
How did you notice that i "released" this Adapter?? I did not announce it anywhere yet? :relaxed:

**Comment by Ilovegym66** [comment]
With the iobroker.info Adapter:
![screenshot_2019-02-24 info - iobroker](https://user-images.githubusercontent.com/36229898/53303644-5169f500-386d-11e9-8681-f7e41aeb3d42.png)

**Comment by BuZZy1337** [comment]
Ahhhh... Okay. 👍 🤣

**Comment by BuZZy1337** [comment]
P.s.: Thanks for the quick feedback - i appreciate that! :relaxed:
