### ISSUE TITLE
monthly Budget 

### ISSUE THREAD

**Issue by Rambo79** [BuZZy1337/ioBroker.roadtraffic#11]
A you sure google gives you a monthly budget? The Adapter ist awesome but my google account says it's just for testing and it will end in 365 days. I get a buget from 265 Euros.

![testversion](https://user-images.githubusercontent.com/42409118/60490350-a77cf800-9ca6-11e9-9e5a-b45a6b942be5.JPG)

![Unbenannt](https://user-images.githubusercontent.com/42409118/60490392-bcf22200-9ca6-11e9-85ff-c665482b9f5a.JPG)

**Comment by stundenblume** [comment]
+1

**Comment by TheMBeat** [comment]
This could help :[Price Sheet from Google]( https://cloud.google.com/maps-platform/pricing/sheet/)

**Comment by BuZZy1337** [comment]
You will get credit every month from google.. Even if the test period is over.

BUT:
The next Version of the Adapter will use the HERE Api .. With HERE you dont have to setup a billing account, just create a free developer account.. :wink:
