### ISSUE TITLE
Loosing object settings if instance setting is changed

### ISSUE THREAD

**Issue by stundenblume** [BuZZy1337/ioBroker.roadtraffic#12]
Hi,
first:
thanks for your nice work!

issue:
I log the duration via object setting into different DB with the SQL and influxDB adapter.
If i change the polling interval in your adapter, I loose the settings in the objects settings. So I have do reconfigure everything.

**Comment by BuZZy1337** [comment]
Fixed in 0.1.0 - please be aware of that the Adapter is now using HERE.com Api (Read the updated Readme here on Github)
