### ISSUE TITLE
Only one Route in Objects

### ISSUE THREAD

**Issue by lapidu** [BuZZy1337/ioBroker.roadtraffic#14]
If i create a second route, the first route is only a datapoint. 

![traffic](https://user-images.githubusercontent.com/28223007/69637027-23ae1880-1058-11ea-9a19-c6daf8acfd61.jpg)

**Comment by BuZZy1337** [comment]
Hi, i am going to release a new version of the Adapter (probably this evening) which is using the HERE Api.. With that Version it will work as expected.. :wink:

**Comment by BuZZy1337** [comment]
Released Version 0.1.0 ..
