### ISSUE TITLE
Feature Request: Timestamp of last successful update per route

### ISSUE THREAD

**Issue by dervitti** [BuZZy1337/ioBroker.roadtraffic#15]
Hey, 
great idea and great work!
In order to update the routes more often at certain times of the day, it would be great to get the Last Update Timestamp to get this done with a script.
And the ability to choose an alternative road would be nice.
best regards
Sebastian

**Comment by BuZZy1337** [comment]
Hi, you can read the timestamp of the state in JavaScript:
```
getState('roadtraffic.0.routes.Name.duration').ts
```

**Comment by dervitti** [comment]
Oh, wonderful! Thanks a lot!
