### ISSUE TITLE
here.com does no longer provice App Codes

### ISSUE THREAD

**Issue by itstartedwithac64** [BuZZy1337/ioBroker.roadtraffic#16]
When followong the link in the readme, creating the app id still works. However here.com changed something and you can only choose to generate either "API Keys" or "OAuth 2.0 Access Key ID".
Neither one of those seems to work.

Which one to choose?

**Comment by dervitti** [comment]
Same problem here. this ist how here.com API Wensite looks now:
![grafik](https://user-images.githubusercontent.com/10255767/70795279-bdd3c780-1d9f-11ea-8b85-2130d15adc4d.png)

**Comment by BuZZy1337** [comment]
Sorry about that.. They removed the App id & App code combination just 2 days after release of the new adapter version..
Im going to release a new version (approximately this weekend) which uses the REST API Key..

**Comment by BuZZy1337** [comment]
Fixed in Version 0.1.1 - please delete all instances of the adapter before doing the update!
