### ISSUE TITLE
Adapter do not start

### ISSUE THREAD

**Issue by lapidu** [BuZZy1337/ioBroker.roadtraffic#17]
After Copy the API Key i become a error

See attachment

![image](https://user-images.githubusercontent.com/28223007/71066979-0d393f80-2174-11ea-916a-31012ec2718b.png)

**Comment by BuZZy1337** [comment]
Did you come from a previous version and this happend after the update to 0.1.1?
Or is this the first time you installed the adapter?

**Comment by lapidu** [comment]
I come from a previous version

**Comment by BuZZy1337** [comment]
Then you have to remove the instance and create a new one.
![image](https://user-images.githubusercontent.com/6979405/71068858-e0872700-2177-11ea-8cf0-4f07ec4d2b70.png)

I had to do some changes to the object structure..
So please be aware that the state names may have changed (check your scripts - if you have any - and set them to use the new stateIDs)..

Sorry about that. :disappointed:

**Comment by lapidu** [comment]
Thank you, its works now. 

You make great work.
