### ISSUE TITLE
since yesterday: unexpected end of json input

### ISSUE THREAD

**Issue by Ilovegym66** [BuZZy1337/ioBroker.roadtraffic#18]
Hi, thank you for the great adapter! Works fine, but since yesterday not any more, I get this error:

roadtraffic.0 | 2019-12-21 08:33:32.491 | error | (28786) API Key check failed: SyntaxError: Unexpected end of JSON input

I've nothing changed...

**Comment by BuZZy1337** [comment]
Seems like Here.com had some issues..
It should work again now.

Can you confirm? Thanks! :relaxed:

**Comment by BuZZy1337** [comment]
Confirmed by other users.
