### ISSUE TITLE
actual version shows thousands of km ..

### ISSUE THREAD

**Issue by Ilovegym66** [BuZZy1337/ioBroker.roadtraffic#2]
Hi, the actual version shows instead of 17km now 17588km to the destination... can it be, thats now are meters?

**Comment by BuZZy1337** [comment]
Yes, I changed it to meters.
There should be a new "text" state which should show it in km.. Can you confirm that?

**Comment by Ilovegym66** [comment]
ok, works fine, my objects wasn't actual.. I've restarted the adapter, and now it works fine. News objects with Text, km and m are there!
thank you, good idea!
